# Generated by Django 5.2.1 on 2025-05-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CosmeticDoctor',
            new_name='Doctor',
        ),
    ]
