# Generated by Django 5.2.1 on 2025-05-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_patient_alter_doctor_contact_number_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='full_name',
        ),
    ]
